apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retro-gaming-ingress
  labels:
    app: retro-gaming
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{DOMAIN_NAME}}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: retro-gaming-service
                port:
                  number: 80
  tls:
    - hosts:
        - {{DOMAIN_NAME}}
      secretName: {{SECRET_NAME}} 
